version: "3.8"

services:
  project:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_started
      mailhog:
        condition: service_started
    restart: on-failure

  db:
    image: postgres:15.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=impacta-health-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

volumes:
  db_data:
